### PR TITLE
Removed call causing undefined behavior

### LINKED ISSUE #4: adsAsynPortDriverCyclicThread freezes when it attemps to connect for the first time on Windows
Even though the project is not compatible with Windows, it is possible to build it using MSVS with some patching of Makefile. Yet, the adsAsynPortDriverCyclicThread freezes on adsLock(). Upon closer inspection, it looks like the cause is the line
```
adsUnlock();
```
in `adsAsynPortDriver::adsAsynPortDriver`. It looks like `adsUnlock()` is called with no `adsLock()` preceding it. `adsUnlock()` uses `std::mutex`. According to https://en.cppreference.com/w/cpp/thread/mutex/unlock, calling `std::mutex::unlock()` while the thread does not own the mutex results into undefined behavior. It seems this has no effect on Linux. Yet, it causes a deadlock on Windows (MSVS 2019). Even though the reason behind it is not known to me, it seems to me this is covered by "undefined behavior" promised in the documentation.

Sadly, I do not have the ADS compatible device available yet. Thus, I cannot test a fix. Therefore, I have created this issue instead of a pull request so the issue can be tracked.

Is this `adsUnlock()` just a forgotten leftover (because there is no call usually protected by `adsLock()/adsUnlock()` before the line in question) or is it any else?

### PR DESCRIPTION
**Pull request by hanak**
Closes #4

### CODE REVIEW

**Comment by hanak** [comment]
Unfortunately, I am not able to test the resulting ads module with an ADS compatible device right now (because I do not have any).

**Comment by tboegi** [comment]
@hanak Thanks for the PR.
Please allow one or two comments:
Since not everybody has access to the issue,
is able to find it, or we may move the Git repo somewhere else,
it is useful to have information from the issue cooked into the
commit message.
So that the commit message includes all information that is 
need for a reader to understand the problem and the solution.

The first thing is the headline, the first line of the commit:
It should indicate the problem in a very short way, so that later
people doing a `git log` are able to find it quickly.
The commit message itself, (separated by an empyt line),
should have the problem description: The information
from the issue, may be cleaned up.
And the solution.

However, I need to dig into the line, if we can remove it for all platforms,
or just Windows. That would take some time.

If you want, ammend your commit by using `git commit --amend`
and then do a "force push" `git push -f`
That way we don't need a new PR, but can improve the existing one

**Comment by hanak** [comment]
@tboegi Thank you for your comments. I have updated the commit message as suggested.

**Comment by tboegi** [comment]
Thanks @hanak 
Fixed in 
8c625ef5656653f71f0ee963f86d879876860049

**Pull request closed without merging**
