### PR TITLE
Remove old (7+ years) commented out code

### PR DESCRIPTION
**Pull request by javicereijo**

### CODE REVIEW

**Comment by mac-kan** [comment]
There are some commented printf statements also. Consider removing those while you are at it.

**Comment by tboegi** [comment]
In the future: Please try to avoid to push to your master branch.
Checkout a side branch (with a useful name) and push that to your own repo.
Thanks, looks good to me

**Comment by javicereijo** [comment]
> There are some commented printf statements also. Consider removing those while you are at it.

Done in new commit.

**Comment by javicereijo** [comment]
> In the future: Please try to avoid to push to your master branch. Checkout a side branch (with a useful name) and push that to your own repo. Thanks, looks good to me

Noted.

**Pull request merged**
